### ISSUE TITLE
LuaJIT instruction set backend?

### ISSUE THREAD

**Issue by decalek** [DQNEO/babygo#88]
LuaJIT [[1]] is one of the fastest tracing compilers [[2]], which due to its size and modest runtime requirements is capable to work in tightly resource restricted environments.

For its speed and efficiency, LuaJIT is popular in many fields e.g. openresty based service frontends (Kong, Apisix), game engines, apps scripting (neovim), scientific computing, and naturally also in the edge computing.

It's JITed CTypes manipulation primitives and FFI works on native speed, which is used in many libraries, including two stable kernel syscall wrappers: ljsyscall [[3]] for Unix-likes and win32 TINN [[4]] for Win32.

Its current architecture/OS support matrix is [[5]], with some non-finished architecture ports [[6]] from external contributors.

IMHO, a go compiler backend targeting the LuaJIT instruction set [[7]][[8]] (and FFI lib), would make many valuable go developments reusable in non-traditional for the go ecosystem fields like e.g. embedded scenarios, still under very acceptable performance. How hard looks such backend?

[[1]] https://repo.or.cz/luajit-2.0.git/blob_plain/HEAD:/doc/luajit.html
[[2]] https://luajit.me/
[[3]] https://github.com/justincormack/ljsyscall/
[[4]] https://github.com/Wiladams/TINN.
[[5]] https://repo.or.cz/luajit-2.0.git/blob_plain/HEAD:/doc/install.html
[[6]] https://github.com/LuaJIT/LuaJIT/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+port%22
[[7]] https://sourcegraph.com/github.com/LuaJIT/LuaJIT@v2.1/-/blob/src/lj_bc.h
[[8]] http://wiki.luajit.org/Bytecode-2.0

[1]: https://repo.or.cz/luajit-2.0.git/blob_plain/HEAD:/doc/luajit.html
[2]: https://luajit.me/
[3]: https://github.com/justincormack/ljsyscall/
[4]: https://github.com/Wiladams/TINN.
[5]: https://repo.or.cz/luajit-2.0.git/blob_plain/HEAD:/doc/install.html
[6]: https://github.com/LuaJIT/LuaJIT/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+port%22
[7]: https://sourcegraph.com/github.com/LuaJIT/LuaJIT@v2.1/-/blob/src/lj_bc.h
[8]: http://wiki.luajit.org/Bytecode-2.0

**Comment by DQNEO** [comment]
Thanks for the info, but the goal of my project is to provider a simple and easy-to-understand compiler for education purpose.
So using a high popular backend language like GNU assembly is better in this case.
